repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [ "--maxkb=500" ]
      - id: debug-statements

  - repo: local
    hooks:
      - id: setup (python)
        name: Setup project
        entry: uv sync
        language: python
        pass_filenames: false
      - id: setup (node)
        name: Setup project
        entry: pnpm
        args: [--dir, learn_nextjs, install]
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-check
        args: [ "--fix" ]
        files: \.py$
        verbose: true
      - id: ruff-format
        files: \.py$
        verbose: true

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        files: \.py$
        verbose: true

      - id: lint-staged
        name: lint-staged
        entry: pnpm
        args: [--dir, learn_nextjs, exec, lint-staged]
        language: system
        pass_filenames: false
