"""user_items_relationship

Revision ID: d8c2bf03d3ff
Revises: b8e9b2c79bb9
Create Date: 2026-03-11 02:35:10.458979

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8c2bf03d3ff"
down_revision: Union[str, Sequence[str], None] = "b8e9b2c79bb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Uuid(), nullable=False))
        batch_op.create_foreign_key(
            "fk_items_user_id_users",
            "users",
            ["user_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_constraint("fk_items_user_id_users", type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
