from typing import Protocol

from learn_fastapi.src.shared.domain.value_object import UserId
from learn_fastapi.src.users.domain.entities import PersistedUser


class UsersRepository(Protocol):
    """Protocol for user repository operations."""

    async def get_user_by_id(self, user_id: UserId) -> PersistedUser | None: ...
    async def get_user_by_email(self, user_email: str) -> PersistedUser | None: ...
    async def get_user_by_refresh_token(
        self, refresh_token: str
    ) -> PersistedUser | None: ...
    async def create_user(self, email: str, password_hash: str) -> PersistedUser: ...
    async def update_user(
        self, user_id: UserId, new_email: str | None, new_password_hash: str | None
    ) -> PersistedUser: ...
    async def delete_user(self, user_id: UserId) -> bool: ...
