# Here you can store secrets like API keys, database URLs, etc. that you don't want to hardcode in your codebase.
# Learn more about Streamlit secrets here: https://docs.streamlit.io/streamlit-cloud
LEARN_FASTAPI_API_URL = "http://localhost:8000/api/v1"
